# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1477616620);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1477616740);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1477623460);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1477616500);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1477616380);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1477616860);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/import/kamen/3/z5134069/prac3");
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 37);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1477623314401");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1477625226401");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1477623345861");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1477626945861");
user_pref("browser.search.countryCode", "AU");
user_pref("browser.search.region", "AU");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160630005308");
user_pref("browser.slowStartup.averageTime", 1595);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":1}");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"pocket-button\",\"firebug-badged-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"loop-button\",\"pocket-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1470208396874");
user_pref("datareporting.sessions.current.activeTicks", 13);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1591);
user_pref("datareporting.sessions.current.main", 30);
user_pref("datareporting.sessions.current.sessionRestored", 1367);
user_pref("datareporting.sessions.current.startTime", "1477622504476");
user_pref("datareporting.sessions.current.totalTime", 1647);
user_pref("datareporting.sessions.currentIndex", 17);
user_pref("datareporting.sessions.previous.15", "{\"s\":1477461816926,\"a\":86,\"t\":1676,\"c\":true,\"m\":30,\"fp\":1624,\"sr\":1554}");
user_pref("datareporting.sessions.previous.16", "{\"s\":1477616138656,\"a\":167,\"t\":6200,\"c\":true,\"m\":100,\"fp\":1871,\"sr\":1943}");
user_pref("datareporting.sessions.prunedIndex", 14);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("e10s.rollout.cohort", "unsupportedChannel");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 16);
user_pref("extensions.blocklist.pingCountVersion", 16);
user_pref("extensions.bootstrappedAddons", "{\"firefox@getpocket.com\":{\"version\":\"1.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"e10srollout@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"loop@mozilla.org\":{\"version\":\"1.3.2\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"47.0.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false},\"firebug@software.joehewitt.com\":{\"version\":\"2.0.15\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/firebug@software.joehewitt.com\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:47.0.1");
user_pref("extensions.firebug.currentVersion", "2.0.15");
user_pref("extensions.firebug.toolbarCustomizationDone2", true);
user_pref("extensions.getAddons.cache.lastUpdate", 1477616620);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "47.0.1");
user_pref("extensions.lastPlatformVersion", "47.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1467249601000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.2\",\"st\":1467249601000},\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.3.2\",\"st\":1467249601000}},\"app-global\":{\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"47.0.1\",\"st\":1467246170000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"47.0.1\",\"st\":1467249601000}},\"app-system-share\":{\"firebug@software.joehewitt.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/firebug@software.joehewitt.com\",\"e\":true,\"v\":\"2.0.15\",\"st\":1459776515000,\"mt\":1458757164000}}}");
user_pref("gecko.buildID", "20160630005308");
user_pref("gecko.mstone", "47.0.1");
user_pref("idle.lastDailyNotification", 1477619125);
user_pref("loop.copy.ticket", 59);
user_pref("media.gmp-manager.buildID", "20160630005308");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1477462228);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1475648265);
user_pref("toolkit.startup.last_success", 1477622504);
user_pref("toolkit.telemetry.cachedClientID", "8daea10d-ef98-4bc3-885b-622ec0fa4d1e");
user_pref("toolkit.telemetry.previousBuildID", "20160630005308");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
